sonar.projectKey=juninmd_quiz-shorts-generator
sonar.organization=juninmd

# By default sonarcloud includes tests in code duplication metrics if they are in sonar.sources.
# This prevents it.
sonar.sources=src
sonar.tests=src/__tests__
sonar.exclusions=src/__tests__/**

# Strictly ignore test duplication
sonar.cpd.exclusions=src/__tests__/**
